source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

pod 'AFNetworking', '~> 2.6.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 2.4.12'
pod 'BaiduMapAPI', '~> 2.8.1'
pod 'ZBarSDK', '~> 1.3.1'
pod 'UITextView+Placeholder', '~> 1.1.0'
pod 'libqrencode', '~> 3.4.2'
pod 'DateTools', '~> 1.6.1'
pod 'EaseMobSDKFull'
pod 'MWPhotoBrowser', '~> 2.1.1'
